# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby-mining"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["arrigonialberto86"]
  s.date = "2013-07-03"
  s.description = "Data mining and machine learning algorithms for JRuby "
  s.email = "arrigonialberto86@gmail.com"
  s.extensions = ["ext/mkrf_conf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".jbundler/classpath.rb",
    "Gemfile",
    "Gemfile.lock",
    "Jarfile",
    "Jarfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/mkrf_conf.rb",
    "features/create_dataset.feature",
    "features/step_definitions/create_dataset.rb",
    "features/step_definitions/weka_parsers.rb",
    "features/support/env.rb",
    "features/weka_parsers.feature",
    "lib/ruby_mining.rb",
    "lib/ruby_mining/apache.rb",
    "lib/ruby_mining/core.rb",
    "lib/ruby_mining/core/parser/parser.rb",
    "lib/ruby_mining/core/type/apache_matrices.rb",
    "lib/ruby_mining/core/type/attribute.rb",
    "lib/ruby_mining/core/type/instance.rb",
    "lib/ruby_mining/core/type/instances.rb",
    "lib/ruby_mining/core/type/utils.rb",
    "lib/ruby_mining/weka.rb",
    "lib/ruby_mining/weka/classifiers/bayes/bayes.rb",
    "lib/ruby_mining/weka/classifiers/bayes/bayes_utils.rb",
    "lib/ruby_mining/weka/classifiers/evaluation.rb",
    "lib/ruby_mining/weka/db/DatabaseUtils_mysql",
    "lib/ruby_mining/weka/db/DatabaseUtils_postgresql",
    "lib/ruby_mining/weka/db/db.rb",
    "lib/ruby_mining/weka/filters/supervised/attribute/attribute.rb",
    "lib/ruby_mining/weka/filters/supervised/instance/instance.rb",
    "lib/ruby_mining/weka/filters/unsupervised/attribute/attribute.rb",
    "lib/ruby_mining/weka/filters/unsupervised/instance/instance.rb",
    "resources/weather.csv",
    "resources/weather.numeric.arff",
    "ruby-mining.gemspec",
    "test/helper.rb",
    "test/test_ruby-mining.rb"
  ]
  s.homepage = "http://github.com/arrigonialberto86/ruby-mining"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Data mining algorithms for JRuby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<jbundler>, [">= 0"])
      s.add_development_dependency(%q<ruport>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<jbundler>, [">= 0"])
      s.add_dependency(%q<ruport>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.3.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<jbundler>, [">= 0"])
    s.add_dependency(%q<ruport>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

